# Generated by Django 4.2.5 on 2023-10-29 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrugDrugInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug1', models.CharField(max_length=255)),
                ('drug2', models.CharField(max_length=255)),
                ('interaction_type', models.CharField(max_length=255)),
                ('severity', models.CharField(max_length=255)),
            ],
        ),
    ]
