# Generated by Django 4.2.5 on 2023-11-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug_interaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATCCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('atc_codes', models.ManyToManyField(related_name='drugs', to='drug_interaction.atccode')),
            ],
        ),
        migrations.CreateModel(
            name='ProductName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='DrugDrugInteraction',
        ),
        migrations.AddField(
            model_name='drug',
            name='product_names',
            field=models.ManyToManyField(related_name='drugs', to='drug_interaction.productname'),
        ),
    ]
