# Generated by Django 5.0.1 on 2024-02-16 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug_interaction', '0002_atccode_drug_productname_delete_drugdruginteraction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='atc_codes',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='product_names',
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions1', to='drug_interaction.drug')),
                ('drug2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions2', to='drug_interaction.drug')),
            ],
        ),
        migrations.DeleteModel(
            name='ATCCode',
        ),
        migrations.DeleteModel(
            name='ProductName',
        ),
    ]
