# Generated by Django 5.0.1 on 2024-02-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug_interaction', '0003_remove_drug_atc_codes_remove_drug_product_names_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='reason',
            field=models.TextField(default=''),
        ),
    ]
